import type { Metadata } from "next";
import { Geist, Pacifico } from "next/font/google";
import "./globals.css";

import Header from "@/components/Header";
import { CartProvider } from "@/context/CartContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const pacifico = Pacifico({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-pacifico",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="da">
      <body
        className={`${geistSans.variable} ${pacifico.variable} antialiased`}
      >
        <CartProvider>
          <Header />
          {children}
        </CartProvider>
    
      </body>
    </html>
  );
}
